--ozone-platform=wayland

--password-store=gnome

--enable-features=WaylandWindowDecorations,VaapiVideoDecoder,ColorPickerPortal

# Enable hardware-accelerated video decode
--enable-accelerated-video-decode

