--ozone-platform=wayland

--enable-features=WaylandWindowDecorations,VaapiVideoDecoder,ColorPickerPortal
--password-store=gnome

# Enable hardware-accelerated video decode
--enable-accelerated-video-decode
