[general]
import = [
  "~/.config/alacritty/theme.toml",
  "~/.config/alacritty/font.toml",
  "~/.config/alacritty/font-size.toml",
]

[terminal]
shell.program = "zsh"

[window]
startup_mode = "Maximized"
blur = true
padding.x = 25
padding.y = 20
opacity = 0.8
decorations = "None"
decorations_theme_variant = "Dark"
