# "$schema" = 'https://starship.rs/config-schema.json'
palette = "oxocarbon"
add_newline = true

[fill]
symbol = ' '

[palettes.oxocarbon]
black = "#161616"
red = "#ee5396"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
magenta = "#be95ff"
cyan = "#3ddbd9"
white = "#dde1e6"

icon = "#161616"
status = "#e23140"

prompt_ok = "#42be65"
prompt_err = "#e23140"

separator = "#45475A"

background = "#262626"
git_branch = "#ffe97b"

directory = "#dde1e6"
duration = "#ee5396"

format = """\
  󰣇 \
  $directory\
  $git_branch$git_commit$git_state $git_status\
  $character\n
"""
continuation_prompt = '▶▶ '


[git_branch]
format = "[](fg:git_branch)[](fg:icon bg:git_branch)[](fg:git_branch bg:background)[ $branch](bg:background)[](fg:background) "
symbol = " "

[git_status]
stashed = ' [ ${count}](blue)'
modified = ' [ ${count}](yellow)'
ahead = ' [ ${count}](green)'
diverged = ' [ ⇡${ahead_count}(green) ⇣${behind_count}(red)](bold purple)'
behind = ' [ ${count}](red)'
staged = ' [ ${count}](green)'
untracked = ' [ ${count}](red)'

# stashed = "[\\($count\\)](blue)"
# modified = " ! ${count}"
# ahead = '⇡${count}(red)'
# diverged = '⇕⇡${ahead_count}⇣${behind_count}'
# behind = '⇣${count}(red)'
# staged = '[++\($count\)](green)'
# untracked = '[??\($count\)](red)'

[git_commit]
tag_symbol = '  '

# ──────────────────────────────
# Language & Tool Symbols
# ──────────────────────────────

[aws]
symbol = " "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "
detect_files = [
  'package.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'package-lock.json',
  '.nvmrc',
  '.node-version',
  'mise.toml',
]

[ocaml]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
