#!/bin/sh
unset NODE_OPTIONS
ELECTRON_RUN_AS_NODE=1 "/opt/visual-studio-code-insiders/code-insiders" "/home/arafays/.config/Code - Insiders/User/globalStorage/github.copilot-chat/copilotCli/copilotCLIShim.js" "$@"