scan_timeout = 100
palette = "oxocarbon"
add_newline = true

# default_format = "$all"

# Move the directory to the second line
format = """
[╭](fg:separator)$directory$all$fill$cmd_duration\
$line_break\
[╰](fg:separator)$character
"""

continuation_prompt = "󰁔 󰁔 "

# format = """
# $line_break\
# [╰](fg:separator)\
# $character\
# """


[palettes.oxocarbon]
black = "#161616"
red = "#ee5396"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
magenta = "#be95ff"
cyan = "#3ddbd9"
white = "#dde1e6"
icon = "#161616"
status = "#e23140"

prompt_ok = "#42be65"
prompt_err = "#e23140"

separator = "#45475A"

background = "#262626"
git_branch = "#ffe97b"

directory = "#dde1e6"
duration = "#ee5396"

[hostname]
ssh_only = true
ssh_symbol = " "
format = ' on [$hostname](bold yellow) '
trim_at = "."
disabled = false

[character]
success_symbol = "[❯](fg:prompt_ok)"
error_symbol = "[❯](fg:prompt_err)"

[status]
format = "[─](fg:separator)[](fg:status)[](fg:icon bg:status)[](fg:status bg:background)[ $status](bg:background)[](fg:background) "
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = "[─](fg:separator)[](fg:status)[](fg:icon bg:status)[](fg:status bg:background)[ $pipestatus](bg:background)[](fg:background) "
disabled = false

[directory]
read_only = " 󰌾"
format = "[─](fg:separator)[](fg:directory)[](fg:icon bg:directory)[](fg:directory bg:background)[ $path](bg:background)[](fg:background)"
truncate_to_repo = false                                                                                                                       # truncates directory to root folder if in github repo
truncation_length = 3
truncation_symbol = "…/"
# repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '
# repo_root_style = 'underline white'

[cmd_duration]
format = "[](fg:duration)[󱐋](fg:icon bg:duration)[](fg:duration bg:background)[ $duration](bg:background)[](fg:background)"
min_time = 4
show_milliseconds = false

[time]
format = "[─](fg:separator)[](fg:duration)[󰥔](fg:icon bg:duration)[](fg:duration bg:background)[ $time](bg:background)[](fg:background) "
disabled = true
time_format = "%H: %M"


[git_branch]
format = "[─](fg:separator)[](fg:git_branch)[](fg:icon bg:git_branch)[](fg:git_branch bg:background)[ $branch](bg:background)[](fg:background) "
symbol = " "

[git_status]
stashed = ' [ ${count}](blue)'
modified = ' [ ${count}](yellow)'
ahead = ' [ ${count}](green)'
diverged = ' [ ⇡${ahead_count}(green) ⇣${behind_count}(red)](bold purple)'
behind = ' [ ${count}](red)'
staged = ' [ ${count}](green)'
untracked = ' [ ${count}](red)'

# stashed = "[\\($count\\)](blue)"
# modified = " ! ${count}"
# ahead = '⇡${count}(red)'
# diverged = '⇕⇡${ahead_count}⇣${behind_count}'
# behind = '⇣${count}(red)'
# staged = '[++\($count\)](green)'
# untracked = '[??\($count\)](red)'

[git_commit]
tag_symbol = '  '

# ──────────────────────────────
# Language & Tool Symbols
# ──────────────────────────────
[aws]
symbol = "  "

[buf]
symbol = "  "

[c]
symbol = "  "

[conda]
symbol = "  "

[crystal]
symbol = "  "

[dart]
symbol = "  "

[docker_context]
symbol = "  "

[elixir]
symbol = "  "

[elm]
symbol = "  "

[fennel]
symbol = "  "

[fossil_branch]
symbol = "  " # nf-oct-git_branch_alt

[golang]
symbol = "  "

[guix_shell]
symbol = "  "

[haskell]
symbol = "  "

[haxe]
symbol = "  "

[hg_branch]
symbol = "  " # nf-oct-git_branch_alt

[java]
symbol = "  "

[julia]
symbol = "  "

[kotlin]
symbol = "  "

[lua]
symbol = "  "

[memory_usage]
symbol = "󰍛  "

[meson]
symbol = "󰔷  "

[nim]
symbol = "󰆥  "

[nix_shell]
symbol = "  "

[nodejs]
symbol = "  "
detect_files = [
  'package.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'package-lock.json',
  '.nvmrc',
  '.node-version',
  'mise.toml',
]

[ocaml]
symbol = "  "

[perl]
symbol = "  "

[php]
symbol = "  "

[pijul_channel]
symbol = "  "

[python]
symbol = "  "

[rlang]
symbol = "󰟔  "

[ruby]
symbol = "  "

[rust]
symbol = "󱘗  "

[scala]
symbol = "  "

[swift]
symbol = "  "

[zig]
symbol = "  "

[gradle]
symbol = "  "

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
