exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(EE5396ff) rgba(1A1A1Aff) 45deg
    col.inactive_border = rgba(1A2420ff) rgba(262626ff) 45deg
}

group {
    col.border_active = rgba(EE5396ff) rgba(1A1A1Aff) 45deg
    col.border_inactive = rgba(1A2420cc) rgba(262626cc) 45deg
    col.border_locked_active = rgba(FFFFFFff) rgba(ABB8B3ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
