exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(BEC3C8ff) rgba(293D52ff) 45deg
    col.inactive_border = rgba(1F232Cff) rgba(4D4C55ff) 45deg
}

group {
    col.border_active = rgba(BEC3C8ff) rgba(293D52ff) 45deg
    col.border_inactive = rgba(1F232Ccc) rgba(4D4C55cc) 45deg
    col.border_locked_active = rgba(121313ff) rgba(0A0A0Aff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
