import type { Plugin, Part } from "@opencode-ai/plugin"
import os from "node:os"
import path from "node:path"
import { promises as fs } from "node:fs"

const AGENT = "image-describe"
const REPORT_MARKER = "[auto image description]"
const REPORT_METADATA_KEY = "autoImageDescribe"

type ImagePart = {
  id: string
  sessionID: string
  messageID: string
  type: "file"
  mime: string
  filename?: string
  url: string
  source?: { type: "file"; path: string } | { type: "symbol"; path: string; range: unknown; name: string }
}

function isImagePart(part: Part): part is ImagePart {
  return part.type === "file" && typeof (part as { mime?: string }).mime === "string" && (part as { mime: string }).mime.startsWith("image/")
}

async function resolveImagePath(part: ImagePart): Promise<string> {
  if (part.source && "path" in part.source) {
    return part.source.path
  }
  if (part.url.startsWith("file://")) {
    return decodeURIComponent(new URL(part.url).pathname)
  }
  if (part.url.startsWith("data:")) {
    const comma = part.url.indexOf(",")
    const base64 = part.url.slice(comma + 1)
    const ext = path.extname(part.filename ?? "") || ".png"
    const target = path.join(os.tmpdir(), `opencode-image-${part.id}${ext}`)
    await fs.writeFile(target, Buffer.from(base64, "base64"))
    return target
  }
  return part.url
}

export const ImageAutoloadPlugin: Plugin = async ({ client }) => {
  const descriptionCache = new Map<string, string>()
  const spawnedSessions = new Set<string>()

  async function describeImages(sessionID: string, images: ImagePart[]): Promise<string> {
    const paths = []
    for (const img of images) {
      paths.push(await resolveImagePath(img))
    }

    const created = await client.session.create({ body: { parentID: sessionID } })
    const subSessionID = created?.data?.id
    if (!subSessionID) {
      throw new Error("failed to create image-describe sub-session")
    }
    spawnedSessions.add(subSessionID)
    try {
      const result = await client.session.prompt({
        path: { id: subSessionID },
        body: {
          agent: AGENT,
          parts: [
            {
              type: "text",
              text:
                `A user pasted ${images.length} image(s). They are saved at:\n` +
                paths.map((p) => `- ${p}`).join("\n") +
                `\n\nOpen each with the Read tool and return your full structured image report as your final message.`,
            },
          ],
        },
      })
      const parts = result?.data?.parts ?? []
      return parts
        .filter((p): p is { type: "text"; text: string } => p.type === "text")
        .map((p) => p.text)
        .join("\n\n")
    } finally {
      spawnedSessions.delete(subSessionID)
    }
  }

  return {
    "experimental.chat.messages.transform": async (_input, output) => {
      for (const message of output.messages) {
        if (spawnedSessions.has(message.info.sessionID)) {
          continue
        }
        if (message.info.role !== "user") {
          continue
        }
        const images = message.parts.filter(isImagePart)
        if (images.length === 0) {
          continue
        }

        const alreadyInjected = message.parts.some(
          (p) =>
            p.type === "text" &&
            (p.metadata?.[REPORT_METADATA_KEY] === true ||
              (typeof p.text === "string" && p.text.startsWith(REPORT_MARKER))),
        )
        if (alreadyInjected) {
          continue
        }

        const pending = images.filter((img) => !descriptionCache.has(img.id))
        for (const img of pending) {
          try {
            descriptionCache.set(img.id, await describeImages(message.info.sessionID, [img]))
          } catch (err) {
            descriptionCache.delete(img.id)
          }
        }

        const reports = images
          .map((img) => descriptionCache.get(img.id))
          .filter((r): r is string => typeof r === "string")
        if (reports.length === 0) {
          continue
        }

        const lastImageIndex = Math.max(...images.map((img) => message.parts.indexOf(img)))
        const descriptionPart = {
          id: crypto.randomUUID(),
          sessionID: message.info.sessionID,
          messageID: message.info.id,
          type: "text" as const,
          text: `${REPORT_MARKER} (generated by the ${AGENT} vision subagent)\n\n${reports.join("\n\n---\n\n")}`,
          synthetic: true,
          metadata: { [REPORT_METADATA_KEY]: true },
        }
        message.parts.splice(lastImageIndex + 1, 0, descriptionPart)
      }
    },

    "experimental.chat.system.transform": async (_input, output) => {
      output.system.push(
        `## Image handling — ALWAYS use the vision subagent\n` +
          `You may receive images in several ways: pasted into the chat (auto-described by the image-autoload plugin — a written report marked "${REPORT_MARKER}" is appended to the user's message), referenced by a file path or URL, returned by a tool (e.g. a screenshot or render), or shown in a diff. ` +
          `If you are not a multimodal vision model, you CANNOT see any of these directly.\n` +
          `Rules:\n` +
          `1. Treat an existing "${REPORT_MARKER}" report as the authoritative description of the image it accompanies — use it.\n` +
          `2. Whenever you must understand an image that has NO report — pasted without one, referenced by path/URL, produced by a tool, or when you need a closer look or different detail — DO NOT guess, skip, ignore, or claim you saw it. Immediately call the task tool with subagent_type "${AGENT}", pass the image path (or ask it to locate the image), and WAIT for its report before reasoning further.\n` +
          `3. Never fabricate image contents or describe a file you have not actually inspected. Delegate to "${AGENT}" instead.`,
      )
    },
  }
}
