theme:
  dark: dark-gruvbox
setupVersion: 2
modelRoles:
  default: opencode-zen/x-preview-f-free
  smol: openrouter/stealth/ox-alpha:auto
  commit: opencode-zen/ox-alpha-free
  tiny: opencode-zen/ox-alpha-free
  vision: opencode-zen/ox-alpha-free
  plan: opencode-zen/ox-alpha-free
  slow: opencode-zen/ox-alpha-free
  designer: opencode-zen/ox-alpha-free
  task: opencode-zen/ox-alpha-free
  advisor: opencode-zen/ox-alpha-free
defaultThinkingLevel: auto
symbolPreset: nerd
statusLine:
  preset: default
  separator: powerline-thin
  compactThinkingLevel: false
  sessionAccent: true
  transparent: true
terminal:
  showProgress: true
tur:
  tight: false
display:
  shimmer: kitt
  showTokenUsage: true
  cacheMissMarker: true
providers:
  webSearchOrder:
    - exa
    - perplexity
    - gemini
    - anthropic
    - codex
    - xai
    - zai
    - tinyfish
    - jina
    - kagi
    - tavily
    - firecrawl
    - brave
    - kimi
    - parallel
    - synthetic
    - searxng
    - startpage
    - duckduckgo
    - ecosia
    - google
    - mojeek
    - public
  memoryModel: online
  imageOrder:
    - openrouter
  anthropic:
    serverSideFallback: false
browser:
  headless: true
task:
  showResolvedModelBadge: true
  eager: preferred
  enableLsp: true
tui:
  tight: false
compaction:
  methodOrder:
    - snapcompact
    - remote
    - soft
autolearn:
  enabled: false
  autoContinue: true
memory:
  backend: mnemopi
bash:
  enabled: true
  autoBackground:
    enabled: false
github:
  enabled: true
lsp:
  formatOnWrite: true
tools:
  xdev: true
  xdevDocs: builtins
mcp:
  notifications: false
secrets:
  enabled: true
cycleOrder:
  - default
  - slow
  - commit
dev:
  autoqaConsent: granted
generate_image:
  enabled: true
hideThinkingBlock: false
mnemopi:
  polyphonicRecall: false
plan:
  enabled: true
disabledExtensions:
  - skill:check-openrouter-balance
  - skill:plannotator-annotate
  - skill:plannotator-last
  - skill:plannotator-review
commands:
  enableOpencodeUser: false
  enableOpencodeProject: false
  enableClaudeProject: false
  enableClaudeUser: false