theme:
  dark: dark-gruvbox
setupVersion: 1
# modelRoles: 
#   default: opencode-go/deepseek-v4-pro:max
#   smol: opencode-go/mimo-v2.5
#   commit: opencode-go/deepseek-v4-flash
#   tiny: opencode-zen/mimo-v2.5-free
#   vision: opencode-go/mimo-v2.5
#   plan: opencode-go/deepseek-v4-pro:high
#   slow: opencode-go/glm-5.2:max
#   designer: opencode-go/kimi-k2.6
#   task: opencode-go/deepseek-v4-pro
#   advisor: opencode-go/deepseek-v4-pro
modelRoles:
  default: deepseek/deepseek-v4-pro
  smol: xiaomi/mimo-v2.5
  commit: deepseek/deepseek-v4-flash
  tiny: deepseek/deepseek-v4-flash
  vision: xiaomi/mimo-v2.5
  plan: deepseek/deepseek-v4-pro
  slow: z-ai/glm-5.2
  designer: moonshotai/kimi-k2.6
  task: deepseek/deepseek-v4-pro
  advisor: deepseek/deepseek-v4-pro
defaultThinkingLevel: auto
symbolPreset: nerd
statusLine:
  preset: default
  separator: powerline-thin
  compactThinkingLevel: false
  sessionAccent: true
  transparent: true
terminal:
  showProgress: true
tur:
  tight: false
display:
  shimmer: kitt
  showTokenUsage: true
  cacheMissMarker: true
providers:
  webSearchOrder:
    - exa
    - perplexity
    - gemini
    - anthropic
    - codex
    - xai
    - zai
    - tinyfish
    - jina
    - kagi
    - tavily
    - firecrawl
    - brave
    - kimi
    - parallel
    - synthetic
    - searxng
    - startpage
    - duckduckgo
    - ecosia
    - google
    - mojeek
    - public
  memoryModel: online
browser:
  headless: true
task:
  showResolvedModelBadge: true
  eager: preffered
  enableLsp: true
tui:
  tight: false
compaction:
  strategy: snapcompact
autolearn:
  enabled: true
  autoContinue: true
memory:
  backend: mnemopi
bash:
  enabled: true
  autoBackground:
    enabled: true
github:
  enabled: true
lsp:
  formatOnWrite: true
tools:
  xdev: true
  xdevDocs: builtins
mcp:
  notifications: false
secrets:
  enabled: true
cycleOrder:
  - default
  - slow
  - commit
dev:
  autoqaConsent: granted
