#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

exec-once = [workspace 1 silent] ~/.config/hypr/scripts/zen-broser-bitwarden.sh  --sleep=3

#
# # Forward bluetooth media commands to MPRIS
# exec-once = mpris-proxy
#
# # Resize and move windows based on matches (e.g. pip)
# exec-once = caelestia resizer -d
# # Start shell
# exec-once = caelestia shell -d
exec-once = hyprpaper & hypridle & dunst

# KDE services (COMMENTED OUT - using Qt6ct instead)
# Uncomment these when switching back to KDE integration
# exec-once = kbuildsycoca6 --noincremental
# exec-once = systemctl --user restart xdg-desktop-portal-kde.service


