# See https://wiki.hypr.land/Configuring/Monitors/
# monitor=,preferred,auto,auto
monitor=HDMI-A-1,1440x900@59,0x0,1,transform,1
monitor=DP-3,2560x1440@59.95,900x0,1

# Workspace rules
workspace = 1, monitor:HDMI-A-1, on-created-empty:kitty, default:true
workspace = 2, monitor:DP-3, on-created-empty:"uwsm app -- /home/arafays/.config/hypr/scripts/zen-browser-bitwarden.sh", default:true
# workspace = 2, monitor:DP-3, on-created-empty:uwsm app -- chromium --restore-last-session --enable-features=UseOzonePlatform --ozone-platform=wayland --profile-directory=Default --disable-features=WaylandWpColorManagerV1, default:true
workspace = 3, monitor:DP-3, default:true
workspace = 4, monitor:DP-3, default:true
workspace = 5, monitor:DP-3, default:true
