"$schema" = "https://raw.githubusercontent.com/HyDE-Project/HyDE/refs/heads/master/Configs/.local/share/hyde/schema/config.toml.json"

[hyprland]
browser = "zen-browser"
editor = "nvim"
explorer = "dolphin"
idle = "hypridle"
terminal = "alacritty"
quickapps = "alacritty -e quickapp"
color_scheme = "prefer-dark"
monospace_font = "CaskaydiaCove Nerd Font Mono"
monospace_font_size = 9


[waybar]
 scale = 10
