# You can find more wallpapers in ~/.config/ml4w/wallpapers/
# Run ~/.config/hypr/reload-hyprpaper.sh after changing your wallpaper
preload = ~/dotfiles/wallpapers/default.jpg
wallpaper = ,~/dotfiles/wallpapers/default.jpg
splash = false

