"$schema" = 'https://starship.rs/config-schema.json'
palette = "noctalia"

scan_timeout = 100
add_newline = true
format = """
[╭](fg:separator) 󰣇 $directory$all$line_break\
[╰](fg:separator) $character
"""

[directory]
read_only = " 󰌾"
truncation_length = 3

[git_branch]
symbol = " "

[git_status]
stashed = ' [ ${count}](blue)'
modified = ' [ ${count}](yellow)'
ahead = ' [ ${count}](green)'
diverged = ' [ ⇡${ahead_count}(green) ⇣${behind_count}(red)](bold purple)'
behind = ' [ ${count}](red)'
staged = ' [ ${count}](green)'
untracked = ' [ ${count}](red)'

[git_commit]
tag_symbol = '  '

[aws]
symbol = " "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
detect_files = [
  'package.json',
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  '.nvmrc',
  '.node-version',
]

[ocaml]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
Kali = " "
Linux = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "


# >>> NOCTALIA STARSHIP PALETTE >>>
# Noctalia Starship Palette (predefined colorscheme)
# Generated by Noctalia - do not edit manually

[palettes.noctalia]
# Standard colors
blue = "#80b3ff"
red = "#ff8080"
green = "#99ffe4"
yellow = "#ffc799"
cyan = "#99ffe4"
magenta = "#fbadff"
white = "#a0a0a0"
black = "#0c0c0c"

# Extended palette (Catppuccin-compatible names)
rosewater = "#ffc799"
flamingo = "#ff8080"
pink = "#fbadff"
mauve = "#fbadff"
maroon = "#ff8080"
peach = "#ffc799"
teal = "#99ffe4"
sky = "#99ffe4"
sapphire = "#80b3ff"
lavender = "#fbadff"

# Text shades
text = "#ffffff"
subtext1 = "#a0a0a0"
subtext0 = "#505050"

# Surface shades
overlay2 = "#505050"
overlay1 = "#505050"
overlay0 = "#0c0c0c"
surface2 = "#0c0c0c"
surface1 = "#0c0c0c"
surface0 = "#0c0c0c"
base = "#0c0c0c"
mantle = "#0c0c0c"
crust = "#0c0c0c"
# <<< NOCTALIA STARSHIP PALETTE <<<
