"$schema" = 'https://starship.rs/config-schema.json'

scan_timeout = 100
palette = "oxocarbon"
add_newline = true
format = """
[╭](fg:separator) 󰣇 $directory$all$line_break\
[╰](fg:separator) $character
"""

[palettes.oxocarbon]
black = "#161616"
red = "#ee5396"
green = "#42be65"
yellow = "#ffe97b"
blue = "#33b1ff"
magenta = "#be95ff"
cyan = "#3ddbd9"
white = "#dde1e6"

icon = "#161616"
status = "#e23140"

prompt_ok = "#42be65"
prompt_err = "#e23140"

separator = "#45475A"

background = "#262626"
git_branch = "#ffe97b"

directory = "#dde1e6"
duration = "#ee5396"

[directory]
read_only = " 󰌾"
truncation_length = 3


[git_branch]
symbol = " "

[git_status]
stashed = ' [ ${count}](blue)'
modified = ' [ ${count}](yellow)'
ahead = ' [ ${count}](green)'
diverged = ' [ ⇡${ahead_count}(green) ⇣${behind_count}(red)](bold purple)'
behind = ' [ ${count}](red)'
staged = ' [ ${count}](green)'
untracked = ' [ ${count}](red)'

[git_commit]
tag_symbol = '  '

[aws]
symbol = " "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[crystal]
symbol = " "

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[golang]
symbol = " "

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[kotlin]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = "󰍛 "

[meson]
symbol = "󰔷 "

[nim]
symbol = "󰆥 "

[nix_shell]
symbol = " "

[nodejs]
detect_files = [
  'package.json',
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  '.nvmrc',
  '.node-version',
]

[ocaml]
symbol = " "

[perl]
symbol = " "

[php]
symbol = " "

[pijul_channel]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "󰟔 "

[ruby]
symbol = " "

[rust]
symbol = "󱘗 "

[scala]
symbol = " "

[swift]
symbol = " "

[zig]
symbol = " "

[gradle]
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
Kali = " "
Linux = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
