XDG_CONFIG_HOME="$HOME/.config"
XDG_DATA_HOME="$HOME/.local/share"
XDG_CACHE_HOME="$HOME/.cache"
XDG_STATE_HOME="$HOME/.local/state"
XDG_CONFIG_DIR="${XDG_CONFIG_DIR:-$HOME/.config}"

QT_QPA_PLATFORMTHEME=qt6ct
QT_QPA_PLATFORM=wayland
QT_WAYLAND_DISABLE_WINDOWDECORATION=1

SDL_VIDEODRIVER=wayland


GTK_THEME_VARIANT=Dark

GDK_BACKEND=wayland

STARSHIP_CONFIG="${XDG_CONFIG_HOME}/starship/starship.toml"
STARSHIP_CACHE="${XDG_CACHE_HOME}/starship"
