QT_QPA_PLATFORMTHEME="qt6ct"
GTK_THEME="adw-gtk3-dark"

# QML runtime
QML_IMPORT_PATH="/etc/xdg/quickshell/noctalia-shell"
QML2_IMPORT_PATH="${QML_IMPORT_PATH}"
QML_DISK_CACHE_PATH="${XDG_CACHE_HOME}/qt6/qmlcache"
