ANDROID_HOME=$HOME/Android/Sdk
ANDROID_SDK_ROOT=$ANDROID_HOME
ANDROID_AVD_HOME=~/.config/.android/avd

JAVA_HOME=/usr/lib/jvm/default

ANDROID_EMULATOR_USE_SYSTEM_LIBS=1

# append android tools to the path
PATH="$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools"
