ANDROID_HOME=${HOME}/Android/Sdk
ANDROID_SDK_ROOT=${ANDROID_HOME}
ANDROID_AVD_HOME=${XDG_CONFIG_HOME}/.android/avd

JAVA_HOME=/usr/lib/jvm/default

ANDROID_EMULATOR_USE_SYSTEM_LIBS=1

PATH=$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools
