## Define the directory where dotfiles are stored
# STOW_DIR: Path to the directory containing dotfiles
STOW_DIR="$HOME/dotfiles"

# Detect AUR wrapper
if pacman -Qi yay &>/dev/null; then
   aurhelper="yay"
elif pacman -Qi paru &>/dev/null; then
   aurhelper="paru"
fi

function in {
    local -a inPkg=("$@")
    local -a arch=()
    local -a aur=()

    for pkg in "${inPkg[@]}"; do
        if pacman -Si "${pkg}" &>/dev/null; then
            arch+=("${pkg}")
        else
            aur+=("${pkg}")
        fi
    done

    if [[ ${#arch[@]} -gt 0 ]]; then
        sudo pacman -S "${arch[@]}"
    fi

    if [[ ${#aur[@]} -gt 0 ]]; then
        ${aurhelper} -S "${aur[@]}"
    fi
}

EDITOR="nvim"
SUDO_EDITOR="$EDITOR"

# cleaning up home folder
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_CONFIG_DIR="${XDG_CONFIG_DIR:-HOME/.config}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
XDG_STATE_HOME="${XDG_STATE_HOME:-$HOME/.local/state}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"
XDG_DESKTOP_DIR="${XDG_DESKTOP_DIR:-$HOME/Desktop}"
XDG_DOWNLOAD_DIR="${XDG_DOWNLOAD_DIR:-$HOME/Downloads}"
XDG_TEMPLATES_DIR="${XDG_TEMPLATES_DIR:-$HOME/Templates}"
XDG_PUBLICSHARE_DIR="${XDG_PUBLICSHARE_DIR:-$HOME/Public}"
XDG_DOCUMENTS_DIR="${XDG_DOCUMENTS_DIR:-$HOME/Documents}"
XDG_MUSIC_DIR="${XDG_MUSIC_DIR:-$HOME/Music}"
XDG_PICTURES_DIR="${XDG_PICTURES_DIR:-$HOME/Pictures}"
XDG_VIDEOS_DIR="${XDG_VIDEOS_DIR:-$HOME/Videos}"
LESSHISTFILE=${LESSHISTFILE:-/tmp/less-hist}
PARALLEL_HOME="$XDG_CONFIG_HOME"/parallel

# wget
WGETRC="${XDG_CONFIG_HOME}/wgetrc"
SCREENRC="$XDG_CONFIG_HOME"/screen/screenrc

MISE_NODE_COREPACK=true
OS_FIREWALL="firewalld"


export XDG_CONFIG_HOME XDG_CONFIG_DIR XDG_DATA_HOME XDG_STATE_HOME XDG_CACHE_HOME XDG_DESKTOP_DIR XDG_DOWNLOAD_DIR \
XDG_TEMPLATES_DIR XDG_PUBLICSHARE_DIR XDG_DOCUMENTS_DIR XDG_MUSIC_DIR XDG_PICTURES_DIR XDG_VIDEOS_DIR STOW_DIR EDITOR SUDO_EDITOR OS_FIREWALL PARALLEL_HOME WGETRC SCREENRC MISE_NODE_COREPACK

alias ff="fzf --preview 'bat --style=numbers --color=always {}'" \
c='clear' \
l='eza -lh --icons=auto' \
la='eza -lha --icons=auto' \
ls='eza -lh --icons=auto --group-directories-first' \
ll='eza -lha --icons=auto --sort=name --group-directories-first' \
ld='eza -lhD --icons=auto' \
lt='eza --icons=auto --tree' \
rg="rg --hidden --glob '!.git'" \
cat="bat" \
scripts="cat package.json | bat --color auto '.scripts'" \
fd='fdfind' \
cd='z' \
n='nvim' \
g='git' \
d='docker' \
lzg='lazygit' \
lzd='lazydocker' \
dev='code .' \
decompress="tar -xzf" \
un='$aurhelper -Rns' \
up='$aurhelper -Syu' \
pl='$aurhelper -Qs' \
pa='$aurhelper -Ss' \
pc='$aurhelper -Sc' \
po='$aurhelper -Qtdq | $aurhelper -Rns -' \
vc='code' \
fastfetch='fastfetch --logo-type kitty' \
..='cd ..' \
...='cd ../..' \
.3='cd ../../..' \
.4='cd ../../../..' \
.5='cd ../../../../..' \
mkdir='mkdir -p' # Always mkdir a path (this doesn't inhibit functionality to make a single dir)

#
# alias zn="kitty @ set-spacing padding=5 && zt; kitty @ set-spacing padding=20"
# alias zs="zn -l welcome"
# alias zt='f() {
#     if [ "$1" = "." ]; then
#         zn attach --create "$(basename $PWD)" --working-dir "$PWD"
#     elif [ -n "$1" ]; then
#         zn attach --create "$1"
#     else
#         zn attach --create "$(basename $PWD)"
#     fi
# }; f'


zn() {
  kitty @ set-spacing padding=5
  zt "$@"
  kitty @ set-spacing padding=20
}

zt() {
  local session_name="${1:-$(basename "$PWD")}"
  zellij attach --create "$session_name" --working-dir "$PWD"
}

zs() {
  zn "welcome"
}

tn() {
  local session_name="${1:-$(basename "$PWD")}"
  kitty @ set-spacing padding=5
  tmux new-session -A -s "$session_name" -c "$PWD"
  kitty @ set-spacing padding=20
}

tt() {
  tn "$@"
}

compress() { tar -czf "${1%/}.tar.gz" "${1%/}"; }
# Convert webm files generated by the Gnome screenshot video recorder to mp4s that are more compatible
webm2mp4() {
  input_file="$1"
  output_file="${input_file%.webm}.mp4"
  ffmpeg -i "$input_file" -c:v libx264 -preset slow -crf 22 -c:a aac -b:a 192k "$output_file"
}
