# Define the directory where dotfiles are stored
# STOW_DIR: Path to the directory containing dotfiles
STOW_DIR="$HOME/.dotfiles"

# Configuration for Zsh history control

# Enable appending to the history file, rather than overwriting it
# when the shell exits.
setopt APPEND_HISTORY

# Ignore duplicate commands and commands that start with a space
# when saving to the history.
HISTCONTROL=ignoreboth

# Set the maximum number of history entries to save in memory.
HISTSIZE=32768

# Set the maximum number of history entries to save in the history file.
HISTFILESIZE="${HISTSIZE}"

# Set the default editor for command-line interface (CLI) to Neovim (nvim)
# This will be used by commands that require an editor, such as git commit
# Also set the editor for sudo commands to the same editor
export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"

export PATH="./bin:$HOME/.local/bin:$HOME/.local/share/omakub/bin:$PATH"
# disable hashcmds to avoid issues with zsh and always use the latest version of the command
unsetopt hashcmds
export OMAKUB_PATH="/home/$USER/.local/share/omakub"

if command --v fzf &> /dev/null; then
    export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border'
    export FZF_CTRL_T_COMMAND="$HOME/.fzf/bin/fzf-tmux --height 40% --layout=reverse --border"
    export FZF_CTRL_T_OPTS="--height 40% --layout=reverse --border"
    eval "$(fzf --zsh)"
fi

if command -v mise &> /dev/null; then
  eval "$(mise activate zsh)"
fi

if command -v zoxide &> /dev/null; then
  eval "$(zoxide init zsh)"
fi


# File system
alias ls='eza -lh --group-directories-first --icons'
alias lsa='ls -a'
alias lt='eza --tree --level=2 --long --icons --git'
alias lta='lt -a'
alias ff="fzf --preview 'batcat --style=numbers --color=always {}'"
alias fd='fdfind'
alias cd='z'

# Tools
alias n='nvim'
alias g='git'
alias d='docker'
alias bat='batcat'
alias lzg='lazygit'
alias lzd='lazydocker'
alias dev='code .'

# Compression
compress() { tar -czf "${1%/}.tar.gz" "${1%/}"; }
alias decompress="tar -xzf"

# Convert webm files generated by the Gnome screenshot video recorder to mp4s that are more compatible
webm2mp4() {
  input_file="$1"
  output_file="${input_file%.webm}.mp4"
  ffmpeg -i "$input_file" -c:v libx264 -preset slow -crf 22 -c:a aac -b:a 192k "$output_file"
}

alias rg="rg --hidden --glob '!.git'"

alias cat="bat"

# corepack aliases
alias yarn="corepack yarn"
alias yarnpkg="corepack yarnpkg"
alias pnpm="corepack pnpm"
alias pnpx="corepack pnpx"
alias npm="corepack npm"
alias npx="corepack npx"

alias scripts="cat package.json | jq --color-output '.scripts'"

# Technicolor dreams
force_color_prompt=yes
color_prompt=yes

PROMPT=$'\uf0a9 '
precmd() { print -Pn "\e]0;%~\a" }

# if starship is not installed, install it
if !command -v starship &> /dev/null; then
    echo "Starship not found. Installing..."
    curl -fsSL https://starship.rs/install.sh | bash -s -- --yes
fi

## Created by Zap installer
[[ -f "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh" ]] ||
    zsh <(curl -s https://raw.githubusercontent.com/zap-zsh/zap/master/install.zsh) --branch release-v1
source "${XDG_DATA_HOME:-$HOME/.local/share}/zap/zap.zsh"

# # # zsh plugins
plug "zdharma-continuum/fast-syntax-highlighting"
# use zsh-mise for polyglot development
plug "wintermi/zsh-mise"
# dont forget to use the command after
# mise use --global usage@latest

plug "MichaelAquilina/zsh-you-should-use"

plug "zap-zsh/supercharge"
plug "zap-zsh/completions"

# # Enable additional plugins
plug "zsh-users/zsh-completions"
plug "zsh-users/zsh-autosuggestions"

plug "mrjohannchang/zsh-interactive-cd"

plugins=(
  copypath
  copyfile
  dirhistory
  docker
  cp
  gh
  fzf
  git
  history
  jsontools
  github
  node
  pnpm
  golang
  npm
  npx
  sudo
)

# auto start zellij
# if command -v zellij &> /dev/null; then
#     eval "$(zellij setup --generate-auto-start zsh)"
# fi
autoload -U +X compinit && compinit
. <( zellij setup --generate-completion zsh | sed -Ee 's/^(_(zellij) ).*/compdef \1\2/' )

alias zt='f() {
    if [ "$1" = "." ]; then
        zellij attach --create "$(basename $PWD)" --working-dir "$PWD"
    elif [ -n "$1" ]; then
        zellij attach --create "$1"
    else
        zellij attach --create "$(basename $PWD)"
    fi
}; f'
# alias zt='f() { if [ -n "$1" ]; then zellij attach --create "$1"; else zellij attach --create $(basename `pwd`); fi; }; f'
alias zs="zellij -l welcome"


# bindkey -v
# export KEYTIMEOUT=1

# # Use vim keys in tab complete menu:
# bindkey -M menuselect 'h' vi-backward-char
# bindkey -M menuselect 'k' vi-up-line-or-history
# bindkey -M menuselect 'l' vi-forward-char
# bindkey -M menuselect 'j' vi-down-line-or-history
# bindkey -v '^?' backward-delete-char

# # Change cursor shape for different vi modes.
# function zle-keymap-select () {
#   case $KEYMAP in
#     vicmd) echo -ne '\e[1 q';;      # block
#     viins|main) echo -ne '\e[5 q';; # beam
#   esac
# }
# zle -N zle-keymap-select
# zle-line-init() {
#     zle -K viins # initiate `vi insert` as keymap (can be removed if `bindkey -V` has been set elsewhere)
#     echo -ne "\e[5 q"
# }
# zle -N zle-line-init

eval "$(starship init zsh)"

# # # To update the gist
# # # gh api --method PATCH -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /gists/3beb86f3b33e396654b1cf1799c923f9 -f "files[.zshrc][content]=$(cat ~/.zshrc)"
