foreground              #FFFFFF
background              #1F232C
selection_foreground    #1F232C
selection_background    #FFFFFF
cursor                  #BEC3C8 
cursor_text_color       #0A0A0A

active_tab_foreground     #1F232C
active_tab_background     #9A7F7A
inactive_tab_foreground   #9A7F7A
inactive_tab_background   #1F232C

# black
color0      #293552
color8      #57688F

# red
color1      #CCE6FF
color9      #AACDF0

# green
color2      #D2CCFF
color10     #B2AAF0

# yellow
color3      #FFD4CC
color11     #F0B5AA

# blue
color4      #9AB1E6
color12     #9AB1E6

# magenta
color5      #A29AE6
color13     #A29AE6

# cyan
color6      #E6A69A
color14     #E6A69A

# white
color7      #CCE6FF
color15     #AACDF0
