foreground              #FFFFFF
background              #0E1114
selection_foreground    #0E1114
selection_background    #FFFFFF
cursor                  #A3897C 
cursor_text_color       #121212

active_tab_foreground     #0E1114
active_tab_background     #86473E
inactive_tab_foreground   #86473E
inactive_tab_background   #0E1114

# black
color0      #293D52
color8      #57738F

# red
color1      #FFDDCC
color9      #F0C1AA

# green
color2      #FFCFCC
color10     #F0AEAA

# yellow
color3      #FFD2CC
color11     #F0B3AA

# blue
color4      #9AC0E6
color12     #9AC0E6

# magenta
color5      #E69E9A
color13     #E69E9A

# cyan
color6      #E6A39A
color14     #E6A39A

# white
color7      #FFDDCC
color15     #F0C1AA




# background              #232323
# selection_foreground    #232323
# selection_background    #FFFFFF
# cursor                  #EE68A3 
# cursor_text_color       #0C0F0E
#
# active_tab_foreground     #232323
# active_tab_background     #C0C1E9
# inactive_tab_foreground   #C0C1E9
# inactive_tab_background   #232323
#
# # black
# color0      #522929
# color8      #8F5757
#
# # red
# color1      #FFCCE2
# color9      #F0AAC9
#
# # green
# color2      #FFCCFF
# color10     #F0AAF0
#
# # yellow
# color3      #CCCDFF
# color11     #AAACF0
#
# # blue
# color4      #E69A9A
# color12     #E69A9A
#
# # magenta
# color5      #E69AE6
# color13     #E69AE6
#
# # cyan
# color6      #9A9CE6
# color14     #9A9CE6
#
# # white
# color7      #FFCCE2
# color15     #F0AAC9
