# Set your personal kitty configuration here

detect_urls yes
copy_on_select yes
allow_remote_control yes

font_size 9.0

font_family MesloLGMDZ Nerd Font Mono

foreground              #FFFFFF
background              #0E1114
selection_foreground    #0E1114
selection_background    #FFFFFF
cursor                  #A3897C 
cursor_text_color       #121212

active_tab_foreground     #0E1114
active_tab_background     #86473E
inactive_tab_foreground   #86473E
inactive_tab_background   #0E1114
# URL underline color when hovering with mouse
url_color               #f5e0dc

# Kitty window border colors
active_border_color     #b4befe
inactive_border_color   #6c7086
bell_border_color       #f9e2af

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

tab_bar_background      #11111b

# Colors for marks (marked text in the terminal)
mark1_foreground #1e1e2e
mark1_background #b4befe
mark2_foreground #1e1e2e
mark2_background #cba6f7
mark3_foreground #1e1e2e
mark3_background #74c7ec

# The 16 terminal colors

# black
color0 #45475a
color8 #585b70

# red
color1 #f38ba8
color9 #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #89b4fa
color12 #89b4fa

# magenta
color5  #f5c2e7
color13 #f5c2e7

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #bac2de
color15 #a6adc8
