# Set your personal kitty configuration here

background_opacity 1
font_size 10

detect_urls yes
copy_on_select yes

# green
    # green "#25be6a"
color2      #25be6a
color10     #167340

# yellow
    # yellow "#ea9d34"
color3      #ea9d34
color11     #9D6210


# white
    # white "#cbd9d8"
color7      #cbd9d8
color15     #F0AAC9
